### ISSUE TITLE
"Waypoint {i} more than 100 ms from previous waypoint" Error When Running Longer Trajectories

### ISSUE THREAD

**Issue by maxwelllls** [pyri-project/pyri-core#7]
When planning and running longer trajectories at slower speeds, the error "Waypoint {i} more than 100 ms from previous waypoint" is encountered. Upon investigation, I found that in the trajectory planning function of the robotics_motion_service, the number of sampled points was limited to 20. After changing this to 40, the system ran normally. The relevant part of the code is as follows:
```
def _generate_movej_trajectory(self, robot_client, rox_robot, q_initial, q_final, speed_perc):
    JointTrajectoryWaypoint = RRN.GetStructureType("com.robotraconteur.robotics.trajectory.JointTrajectoryWaypoint", robot_client)
    JointTrajectory = RRN.GetStructureType("com.robotraconteur.robotics.trajectory.JointTrajectory", robot_client)

    dof = len(rox_robot.joint_type)

    N_samples = math.ceil(np.max(np.abs(q_final-q_initial))*0.2*180/np.pi)
    # N_samples = np.max((N_samples,20))
    N_samples = np.max((N_samples,40))
```
Suggestion: Should we consider subdividing the sampling points based on time?

BTW, in the function that prints the "Waypoint {i} more than 100 ms from previous waypoint" error, there is a missing 'f' in front of the string, which results in the value of 'i' not being printed.

**Comment by johnwason** [comment]
Hi @maxwelllls, I am going to be replacing the path generation with `tesseract-robotics`  (https://github.com/tesseract-robotics/tesseract) sometime this spring so I would suggest using the modification that is working for you. The check in the driver was added to increase the interpolation accuracy on that side, but that might have been made after this package was created.

Can I ask what organization you are with and what robot model you are using?

**Comment by johnwason** [comment]
@maxwelllls oh you said it was a "Realman RML63" on the other issue. What driver are you using?

**Comment by maxwelllls** [comment]
We are a small robotics research group named Boomy Robot, currently developing a robot product based on ROS2. We use EtherCAT, ros2_control, and MoveIt2 for the control and planning of the robotic arm. However, RViz is clearly not suitable as a product-level robot teaching interface. After some research, we discovered the PyRI Teach Pendant project, which seems to meet our current needs.

I started last Friday to deploy the PyRI environment on our controller. To get familiar with this framework, we first used a mature robot product, [Realman RML63](https://www.realman-robotics.com/RML63xilie/648.html), which uses a TCP+JSON communication protocol, making it easier to develop and use. I wrote a Python driver program based on the Gazebo example code, and it's already running properly.

Next, I plan to use PyRI ROS2 bridge to directly control our robot's movements and try to leverage MoveIt2 components for improved trajectory planning, kinematic interpolation, obstacle avoidance, and singularity avoidance, among other functionalities.

**Comment by johnwason** [comment]
That's great! We have a directory of drivers we can add yours to if you are open-sourcing it: https://github.com/robotraconteur/robotraconteur-directory

PyRI is designed to use Tesseract which has similar capabilities to MoveIt but is a simpler library to work with. There is a rough module for PyRI, but it may not have been updated to the current version of Tesseract: https://github.com/pyri-project/pyri-tesseract-planning

Also see https://github.com/tesseract-robotics/tesseract_python and https://github.com/tesseract-robotics/tesseract_robotraconteur for more information on the Tesseract library.

**Comment by maxwelllls** [comment]
I am happy to share some of my recent work results. I will be submitting a pull request to you soon.

**Comment by maxwelllls** [comment]
@johnwason The driver for the Realman Robot has been uploaded to [this repository](https://github.com/maxwelllls/RealmanRobotRaconteurDriver). Please fork it into robotraconteur-contrib.

**Comment by johnwason** [comment]
Nice work @maxwelllls! Do you have permission to redistribute `libRM_Base.so.1.0.0`? I would not recommend redistributing vendor software binaries unless you have explicit permission or the license allows. Here are instructions to purge a file if necessary: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by maxwelllls** [comment]
This .so file is provided by the manufacturer, and I likely do not have the distribution rights. I can use socket to implement these API functions myself, and I will replace this content later.

**Comment by johnwason** [comment]
We have had better luck with C# based drivers vs Python based drivers for robots where performance is important. The ABB driver is pretty simple and should be straightforward to modify to use JSON: https://github.com/robotraconteur-contrib/ABBRobotRaconteurDriver

**Comment by maxwelllls** [comment]
I am more familiar with Python and have already written a few necessary interface functions and conducted some basic tests. Please review them, and if there are any issues, let me know.

**Comment by maxwelllls** [comment]
> PyRI is designed to use Tesseract which has similar capabilities to MoveIt but is a simpler library to work with. There is a rough module for PyRI, but it may not have been updated to the current version of Tesseract: https://github.com/pyri-project/pyri-tesseract-planning

If I want to use the robot's built-in moveL, moveC path planning functionalities, or the APIs provided by MoveIt, should I replace the pyri-robotics component with the pyri-robotics-motion-program component, and then develop the corresponding robotics-motion-program driver for the robot?

 From my understanding, the purpose behind designing the pyri-robotics-motion-program seems to be to enable continuous trajectory control for ABB robots. Are there any suggestions?

**Comment by johnwason** [comment]
The motion program interface is designed to use the built-in robot controller for motion generation rather than using an external streaming control interface such as EGM. For the PyRI motion program code, it is designed to use something like https://github.com/rpirobotics/abb_motion_program_exec driver.

The motion program interface is less developed and the API should be considered unstable.  I am probably going to rework the interface to merge it with the current standard robot later this year. Also the jogging does not currently work without the streaming interface.

**Comment by maxwelllls** [comment]
So, could I directly base my work on the standard robot, adding functions such as nativeMoveL, nativeMoveC, nativeJogL that directly call the robot's own APIs, bypassing the planning part and sending commands directly to the robot?

If this aligns with your thoughts, I will start working on it soon.

**Comment by johnwason** [comment]
The abb hmp driver is a hybrid driver that supports both the streaming and motion program mode. The driver is quite a bit more complicated than the other drivers, but it is able to support all modes. I have not settled on the best design for this type of driver yet.

https://github.com/robotraconteur-contrib/abb_robotraconteur_driver_hmp
